package: cache_warmup
version: '3.7.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cache_warmup

page:
    title: translate:title
    perm: admin
    popup: true
    hidden: true
    subpages:
        warmup:
            title: translate:title
            popup: true
            hidden: true
        generator:
            title: generator
            hidden: true
            hasLayout: false

pages:
    system/cache_warmup:
        title: translate:title
        perm: admin
        subpages:
            start: { title: translate:page_start }
            readme: { title: translate:page_readme, subPath: README.md }

requires:
    redaxo: '^5.2'
    php: '>=7.1'

# define conflicts: prevents packages from update to avoid breaking changes
# https://github.com/FriendsOfREDAXO/cache_warmup/pull/55#issuecomment-280906737
conflicts:
    packages:
        media_manager: '>=3'
        metainfo: '>=3'
        structure: '>=3'
